import { useEffect, useState } from "react";
import { Edit3, Plus, Trash2 } from "lucide-react";
import GalleryFilters from "../../components/gallery/GalleryFilters";
import { useCreateCohort, useCreateGalleryItem, useGalleryItems, useGalleryMetadata, useUpdateGalleryItem, useDeleteGalleryItem, useUploadGalleryImage } from "../../hooks/useGallery";

const blankEntry = { name: "", role: "student", cohort: "", category: "", bio: "", year: new Date().getFullYear(), isPublished: true, displayOnHomepage: false, imageUrl: "" };
const GalleryManagement = () => {
  const [filters, setFilters] = useState({ search: "", year: "", cohort: "", category: "", role: "" });
  const [page, setPage] = useState(1); const [entry, setEntry] = useState(blankEntry); const [file, setFile] = useState(null); const [open, setOpen] = useState(false); const [cohortOpen, setCohortOpen] = useState(false); const [cohort, setCohort] = useState({ name: "", year: new Date().getFullYear(), description: "" });
  const metadata = useGalleryMetadata(); const listFilters = { ...filters, all: true, page, limit: 20 }; Object.keys(listFilters).forEach((key) => !listFilters[key] && delete listFilters[key]);
  const { data, isLoading, error } = useGalleryItems(listFilters, true); const create = useCreateGalleryItem(); const update = useUpdateGalleryItem(); const remove = useDeleteGalleryItem(); const upload = useUploadGalleryImage(); const createCohort = useCreateCohort();
  useEffect(() => { setPage(1); }, [filters]);
  const editing = Boolean(entry.galleryId); const mutating = create.isPending || update.isPending || upload.isPending;
  const change = (key, value) => setEntry((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); let imageUrl = entry.imageUrl; if (file) imageUrl = (await upload.mutateAsync(file)).data.imageUrl; const payload = { ...entry, imageUrl, year: Number(entry.year) }; if (editing) await update.mutateAsync({ ...payload, id: entry.galleryId }); else await create.mutateAsync(payload); setOpen(false); setEntry(blankEntry); setFile(null); };
  const selectFile = (event) => { const selected = event.target.files?.[0]; if (!selected) return; if (!["image/jpeg", "image/png", "image/webp"].includes(selected.type) || selected.size > 5 * 1024 * 1024) { window.alert("Upload a JPEG, PNG, or WebP image that is 5 MB or smaller."); event.target.value = ""; return; } setFile(selected); };
  const submitCohort = async (event) => { event.preventDefault(); await createCohort.mutateAsync({ ...cohort, year: Number(cohort.year) }); setCohortOpen(false); setCohort({ name: "", year: new Date().getFullYear(), description: "" }); };
  return <div className="p-4 pt-20 lg:p-7 lg:pt-7"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-gray-900">Gallery management</h1><p className="mt-1 text-gray-600">Manage people, cohort content, publication, and homepage selection.</p></div><div className="flex gap-2"><button type="button" onClick={() => setCohortOpen(true)} className="rounded border border-primary px-4 py-2 font-medium text-primary">Add cohort</button><button type="button" onClick={() => { setEntry(blankEntry); setFile(null); setOpen(true); }} className="flex items-center gap-2 rounded bg-primary px-4 py-2 font-medium text-white"><Plus size={18} /> Add entry</button></div></div><GalleryFilters filters={filters} metadata={metadata.data} onChange={(key, value) => setFilters((current) => ({ ...current, [key]: value }))} onReset={() => setFilters({ search: "", year: "", cohort: "", category: "", role: "" })} />
  {error ? <p className="mt-8 rounded bg-red-50 p-4 text-red-800">Unable to load gallery content.</p> : isLoading ? <p className="py-10 text-gray-600">Loading gallery content...</p> : <><div className="mt-6 overflow-x-auto rounded-lg border bg-white"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-gray-50 text-gray-600"><tr><th className="p-3">Person</th><th>Cohort</th><th>Category</th><th>Status</th><th>Homepage</th><th className="p-3">Actions</th></tr></thead><tbody>{data?.items?.map((item) => <tr key={item.galleryId} className="border-t"><td className="p-3"><div className="flex items-center gap-3"><img src={item.imageUrl} alt="" className="h-10 w-10 rounded object-cover" /><span><strong className="block">{item.name}</strong><small className="capitalize text-gray-500">{item.role}</small></span></div></td><td>{item.cohort} ({item.year})</td><td>{item.category}</td><td><button type="button" onClick={() => update.mutate({ id: item.galleryId, isPublished: !item.isPublished })} className={`rounded px-2 py-1 text-xs font-semibold ${item.isPublished ? "bg-green-100 text-green-800" : "bg-gray-200 text-gray-700"}`}>{item.isPublished ? "Published" : "Draft"}</button></td><td><input aria-label={`Show ${item.name} on homepage`} type="checkbox" checked={item.displayOnHomepage ?? item.isFeatured} onChange={() => update.mutate({ id: item.galleryId, displayOnHomepage: !(item.displayOnHomepage ?? item.isFeatured) })} /></td><td className="p-3"><div className="flex gap-2"><button aria-label={`Edit ${item.name}`} type="button" onClick={() => { setEntry({ ...item, displayOnHomepage: item.displayOnHomepage ?? item.isFeatured }); setFile(null); setOpen(true); }} className="rounded p-2 text-primary hover:bg-blue-50"><Edit3 size={17} /></button><button aria-label={`Delete ${item.name}`} type="button" onClick={() => window.confirm(`Delete ${item.name}?`) && remove.mutate(item.galleryId)} className="rounded p-2 text-red-700 hover:bg-red-50"><Trash2 size={17} /></button></div></td></tr>)}</tbody></table></div>{!data?.items?.length && <p className="py-10 text-center text-gray-600">No gallery entries match these filters.</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-2 disabled:opacity-40">Previous</button><button type="button" disabled={page >= (data?.pagination?.pages || 1)} onClick={() => setPage(page + 1)} className="rounded bg-primary px-3 py-2 text-white disabled:opacity-40">Next</button></div></>}
    {open && <Modal title={editing ? "Edit gallery entry" : "Add gallery entry"} close={() => setOpen(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><input required value={entry.name} onChange={(e) => change("name", e.target.value)} /></Field><Field label="Person type"><select value={entry.role} onChange={(e) => change("role", e.target.value)}><option value="student">Student</option><option value="trainer">Trainer</option></select></Field><Field label="Cohort"><input required value={entry.cohort} onChange={(e) => change("cohort", e.target.value)} placeholder="e.g. Cohort A" /></Field><Field label="Year"><input required type="number" min="2000" max="2100" value={entry.year} onChange={(e) => change("year", e.target.value)} /></Field><Field label="Category"><input required value={entry.category} onChange={(e) => change("category", e.target.value)} placeholder="e.g. Robotics" /></Field><Field label="Image"><input required={!editing} type="file" accept="image/jpeg,image/png,image/webp" onChange={selectFile} /><small className="text-gray-500">JPEG, PNG or WebP. Maximum 5 MB.</small></Field><Field label="Bio" full><textarea value={entry.bio || ""} onChange={(e) => change("bio", e.target.value)} rows="3" /></Field><label className="flex items-center gap-2"><input type="checkbox" checked={entry.isPublished} onChange={(e) => change("isPublished", e.target.checked)} /> Publish publicly</label><label className="flex items-center gap-2"><input type="checkbox" checked={entry.displayOnHomepage} onChange={(e) => change("displayOnHomepage", e.target.checked)} /> Display on homepage</label><div className="sm:col-span-2 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded border px-4 py-2">Cancel</button><button disabled={mutating} className="rounded bg-primary px-4 py-2 text-white disabled:opacity-50">{mutating ? "Saving..." : "Save entry"}</button></div></form></Modal>}
  {cohortOpen && <Modal title="Add cohort" close={() => setCohortOpen(false)}><form onSubmit={submitCohort} className="grid gap-4"><Field label="Cohort name"><input required value={cohort.name} onChange={(e) => setCohort({ ...cohort, name: e.target.value })} /></Field><Field label="Year"><input required type="number" min="2000" max="2100" value={cohort.year} onChange={(e) => setCohort({ ...cohort, year: e.target.value })} /></Field><Field label="Description"><textarea value={cohort.description} onChange={(e) => setCohort({ ...cohort, description: e.target.value })} /></Field><button disabled={createCohort.isPending} className="rounded bg-primary px-4 py-2 text-white">Save cohort</button></form></Modal>}</div>;
};
const Field = ({ label, children, full = false }) => <label className={full ? "sm:col-span-2" : ""}><span className="mb-1 block text-sm font-medium text-gray-700">{label}</span>{children}</label>;
const Modal = ({ title, close, children }) => <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/50 p-4" onMouseDown={(e) => e.target === e.currentTarget && close()}><section role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-lg bg-white p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button type="button" aria-label="Close" onClick={close}>Close</button></div>{children}</section></div>;
export default GalleryManagement;
